### ISSUE TITLE
 !changemapsetting

### ISSUE THREAD

**Issue by Chobbz** [NadalB/Precision-Playhouse-Assault-cube-server#10]
Hey

First don't forget to allow "run" as an arg OR say speedrun in the !help changemapsetting / !setmapsetting display

Then when we !changemapsetting 20 casual hard for example nothing happens (No confirmation message unless it fails.) ALSO Time is not changing. only type and difficulty.

**Comment by NadalB** [comment]
Message coming as soon as score fixed

**Comment by NadalB** [comment]
if you vote the exact map not by gonext the time will be 15min by ac default i wont change that because it remove the ability to vote the map by a different time
