### ISSUE TITLE
Deleteservermap & changesetting stil buggy

### ISSUE THREAD

**Issue by Chobbz** [NadalB/Precision-Playhouse-Assault-cube-server#11]
whenever I setmapsetting /changemapsetting time remains 20 when i set a map. yesterday I tried to delete a servermap server crsahed before I get response. Today the map was deleted so I thought it was fixed b ut again it crashed the server.

**Comment by NadalB** [comment]
this one fixed by 2 hour ago test it if im wrong

**Comment by NadalB** [comment]
also if u /ctf map then the time is the default only works with gonext

**Comment by NadalB** [comment]
there is a chance thats an other thing like i fixed before

**Comment by NadalB** [comment]
dont have time for more tryhard fixes so maybe an another try tomorow try to avoid deleteservermap today other things 80% have to work

**Comment by Chobbz** [comment]
oh yeah I used to /Ctf so thats why. I thought of something and monte agreed : don't you have any way like in coop edit mode to just set infinite time for every gemas ? We always gonext manually and never let time end. 
I won't use deleteservermap then until its fixed

**Comment by NadalB** [comment]
i have a solution for coop edit but the time cannot be used in votes cuz its remove the ability to vote a map by a time u want

**Comment by NadalB** [comment]
coop will be like u set it by settings thats only can be voted by coop only need a solution fot who can update how admins can or just the author but think about a coop server which allow to coop there and just pull the map if finished

**Comment by NadalB** [comment]
also i think there is a way to set a time like 5k minutes but idk if its a good thing or not idk if i can make infinite i have to check coop mode for how is it work this way

**Comment by Chobbz** [comment]
To me its good thing. we go next when we finish the map / are done running. Time  left IS NEVER  decisive in gema unless to screw us up when we don't pay attention

**Comment by NadalB** [comment]
ye ik but for every one idk if its better if irts never ending

**Comment by Chobbz** [comment]
when people finished the map they always do /gonext 5 or vote one they like we don't wait time goes off also as its private server we all know that

btw im doing my map and i have question. do I need to send you my custom textures I made so you add them to the pkg so people have it or theres a way to automatically download it on AC ?

**Comment by NadalB** [comment]
you have to send me to upload to the pkg server

**Comment by NadalB** [comment]
there is a chance for it solved tried to upload and remove the same map u tried and a couple other

**Comment by Chobbz** [comment]
Alright will try, also we keep having randomly this bug where we vote a map and its a compelte another map showing up.
How do I send you the files?

**Comment by NadalB** [comment]
upload them somewhere and send it to the email i think thats the easiest way to do it, about the random map votes no idea cuz there is nothing obvious that can cause this

**Comment by NadalB** [comment]
only thing when you compress then compress the order like in the textures folder in your packages dont send me just the raw textures otherwise u have to change them in the folder i set like textures/Chobbz/jpgshere

**Comment by Chobbz** [comment]
Hey, most bug looks fixed for now however I found this https://gyazo.com/1e053da538950e6ae9410e0e5dd683b3 
I think I told you about it before not sure tho problem is display : it says stays at X place while I actually get a higher place that I had

**Comment by NadalB** [comment]
![20230827_07 20 25_gema_kazumi_CTF](https://github.com/NadalB/Precision-Playhouse-Assault-cube-server/assets/51461994/5e422e86-efae-461c-a2f6-daf7d88ea1c0)
There was a variable that had to check if rank improves but it was never changed/checked so it was always false
