### ISSUE TITLE
Crash editaccount

### ISSUE THREAD

**Issue by Chobbz** [NadalB/Precision-Playhouse-Assault-cube-server#12]
Hey

Today I tried to test out upload access earned with experience points. To test this I wanted to add EXP to my TestingPlayer account and when I did server crashed. "!editaccount testingplayer playerExperience 4999" is what I entered

**Comment by NadalB** [comment]
checked wrong column in sql, so now its probably fixed

**Comment by Chobbz** [comment]
Okay EDITACCOUNT looks fixed.

so I kept further my test I logged in with my 4999 exp account, 1exp close to reach the uplaod access. Account had at this moment only PLAY role. idk if it's related to the upload access getting unlocked or just a bug you awake while fixing editaccount but when I tried to score server crashed instantly while touching my team's flag.
also if you change code again could you not forget the changesubaccess thing pls ?

**Comment by NadalB** [comment]
probably many of the score related thing now not wornking because od smart pointers not all just some

**Comment by NadalB** [comment]
![20230829_15 43 57_gema-test3_CTF](https://github.com/NadalB/Precision-Playhouse-Assault-cube-server/assets/51461994/90537dd1-0707-483a-99a2-230e25a70ddc)
This now works but there is a chance for more like this by the rework on score manager/system.
maybe a better msg needed "accesses" only this one use changeaccess automatically
also before you test it again i tell you how is it work. basicly it add every Role letter together which you held and if you dont have upload access then add to them and change it
