### ISSUE TITLE
Wohoo

### ISSUE THREAD

**Issue by Chobbz** [NadalB/Precision-Playhouse-Assault-cube-server#13]
Helloo

I saw you restarted server I was like let's check in case he did AND HE DID !! subaccess is out lads ! xd
Okay everything works great with but I found a weird interaction. if I add to TestingPlayer the subaccess RACIST (or any other one) it will be granted but when I connect to the server colours don't show. It looks like the target needs to be connected to the server when doing changesubaccess or else it won't set the colours despite the role being added. That's the only little "bug" I've found with it

Ty tho !

**Comment by NadalB** [comment]
probably forgot to add an another exception, i made the server use less on the database which kinda faster now on the accounts

**Comment by Chobbz** [comment]
I tested it earlier today and it looked fixed but it looks like we are having the same issue with classic roles ( !changeaccess ) if the player is not connected while his access is being changed it will just won't apply even if he connects/disconnects after

**Comment by NadalB** [comment]
fixed
