### ISSUE TITLE
Another db bug?

### ISSUE THREAD

**Issue by Chobbz** [NadalB/Precision-Playhouse-Assault-cube-server#14]
Hey, looks like !editaccount doesn't work it says invalid account or type 
both for psw and playerexperience

**Comment by NadalB** [comment]
dont think so, its case sensitive now 100% did u tried the exact name with uppercase if it have, if not this is the case there is an exception which i left feom the older version which may block it

**Comment by Chobbz** [comment]
yeah I saw lowercase was important now with commands but I'm 100% sure it was the correct name I did !editaccount Chobbz playerExperience 6969 didn't work same with !editaccount Chobbz password testtest

**Comment by NadalB** [comment]
did u tried with account chobbz?

**Comment by NadalB** [comment]
nevermind found the problem

**Comment by Chobbz** [comment]
Y i tried with my acc
👍🏻

**Comment by NadalB** [comment]
i made aome restrict which only allow like for now chobbz only edit those account which is lower roles or itself but nothing will happen on editing chobbz by chobbz becasue nothing implemented in the code where it have to happen just the if statement which is true but logically it have to continue  with the bext id statement which is true so its a bit illogical ill try it if it work the way it implemented

**Comment by Chobbz** [comment]
I tried today with testingplayer it didnt work

**Comment by NadalB** [comment]
i did nothing with it maybe thats why

**Comment by NadalB** [comment]
probably working
