### ISSUE TITLE
infinite pickups

### ISSUE THREAD

**Issue by Chobbz** [NadalB/Precision-Playhouse-Assault-cube-server#15]
Hey

Outside of gema mod (douze desert and all stuff like this) there are infinite ammount of pickups.

**Comment by NadalB** [comment]
nice, probably when i edited removed the part that restrict outdide gema mode

**Comment by NadalB** [comment]
i think its the spawn time only thing that check gema mode is the +2 pickup that sent once which makes it faster than just respawn the pickup in some millis

**Comment by NadalB** [comment]
solved it was just the timer which always got millis instead of seconds cuz of *1 instead of 1000
