### ISSUE TITLE
Auto ban

### ISSUE THREAD

**Issue by Chobbz** [NadalB/Precision-Playhouse-Assault-cube-server#5]
Hey

server network error, disconnecting (client num) ...
Had this while playing on the gema I uploaded (gema phoenix 94). I suspect anti cheat as its autoban for some reasons. It was when I was in the clipped skymap part I got auto banned sadly can't even reconnect xd
Edit reconnected with vpn removed bans but happened to me again in same map but different spot.
Mbe demo is available

**Comment by Kenjov** [comment]
was it unreachable part?

**Comment by NadalB** [comment]
if it was unreacable then otherwise ill check
