### ISSUE TITLE
Bugs & ideas

### ISSUE THREAD

**Issue by Chobbz** [NadalB/Precision-Playhouse-Assault-cube-server#6]
Hey

Okay so I found 4 notworkingwell things with the same feature : deleterecords.

First if you delete record of someone in a map using this !deleterecord NAME WEAPON it will say "[Error] Deleted record temponary" but will actually delete it so no reason to say Error.

Second is with the first. Once you removed it once you can re use the command despite the record being removed it will not say record doesn't exist but put the error (which is not) message again.

Third is not really a bug but when doing !help deleterecord it doesn't have weapon name as  arg2 to be set. also would be maybe a good idea to add the weapon name shortcuts cuz it's not that easy to know sr is for sniper for example. !Removerecord doesn't either show any arg instead of showing arg1 weapon name.

Idea : Maybe add as its only for admins+ /cleardemos for !cmds in admins section ?

4th, if you're using an alias (logged in with an account that you don't currently wear the name of) you can't do !removerecord you need to rename yourself the original one.

Special interaction I found : you have ChobbzTest logged in with Player role only. He renames himself Poppy. If someone !changeaccess to chobbztest to PUMA for example, if he was renamed Poppy he will remain with P role only until he reconnects. Also works the opposite way : if ChobbzTest logged in with alias Poppy while being both being admin, if access is set to Player only to ChobbzTest then Poppy remains admin and able to use any command even able to changeaccess to ChobbzTest back to something like PUM if doesn't disconnect meanwhile. While if the name was not changed access is immediately downagraded. 

Okay thats a lot I don't know if you care that much of everything or if some things are intended or not but hope this helps !

Chobbz

**Comment by Chobbz** [comment]
https://gyazo.com/025785b5bf80046208ae37cc100703c1

**Comment by NadalB** [comment]
weapons have shorter args but i forgot to add it to help command i think if u type just !deleterecord it will tell u

**Comment by NadalB** [comment]
4th i wont make it work that way so u have to logout before u log in to an other

**Comment by NadalB** [comment]
last one probably search for name not logged name thats an ez fix

**Comment by Chobbz** [comment]
> weapons have shorter args but i forgot to add it to help command i think if u type just !deleterecord it will tell u

hm no I tried it doesn't

for 4th I don't really get what you meant. Maybe you didn't understand me. Problem is not switching accounts problem is if you rename while being loggedit will not erase the loggedname if you wear alias. to me the problem is when you do !removerecord it checks for current name instead of logged in name

EDIT: yeah for 4th it works this way. Problem if you don't fix it is this : I score as Chobbz logged in. I log out. I login with ChobbzTest and rename myself Chobbz. I can !removerecord AR and it will remove record of Chobbz !!! Doable with pretty much anybody. So you gotta fix

**Comment by NadalB** [comment]
i thought u meant it wont work with an other account if u logged to an other but it check for name sure i checked

**Comment by NadalB** [comment]
but i checked if u type !removerecord that show the weapon list without type any arg but probably forgot on deleterecord it was if u used 'weapon' as an argument but it was after name so i changed to weapon and name so u can type without arg or type weapon after

**Comment by NadalB** [comment]
but thatks for the issues its help a lot

**Comment by NadalB** [comment]
cleardemos wont be on the list other things i think done
