### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by Chobbz** [NadalB/Precision-Playhouse-Assault-cube-server#8]
hi been twice since yesterday that server crashes when I try to score

**Comment by NadalB** [comment]
is it when u get the flag or on score?

**Comment by Chobbz** [comment]
I take ennemy flag no problem if I try to score by sitting on my own flag with ennemy's it doesn't and crash

**Comment by NadalB** [comment]
looks like solved need more runtime to confirm

**Comment by NadalB** [comment]
open again if it occur
