### ISSUE TITLE
Maptop 

### ISSUE THREAD

**Issue by Chobbz** [NadalB/Precision-Playhouse-Assault-cube-server#9]
Hello,

New bug, an image speaks more than a text
https://gyazo.com/c506eec19bcced92391ed9d65d8e51af

PS: remember when we talked about that time thing in mapsettings and I said 1mn should be possible... I thought it was an indicator time to how long it would take to complete the map, not the game time for the map ahah now I understand why can't under 15 ! Aso I saw you fixed averages of !ratemap. But still can't see map stats : what is it supposed to show ? Also don't forget that sub access thing !!

Chobbz

**Comment by NadalB** [comment]
i think i know whats the cause of the bug but it will take time which i dont really have so if u can dont try to do it by changed name or so

**Comment by Chobbz** [comment]
Sure, it was unintended anyway I'll delete that record and avoid changing

**Comment by NadalB** [comment]
![20230818_17 21 51_gema-test3_CTF](https://github.com/NadalB/Precision-Playhouse-Assault-cube-server/assets/51461994/fe1de673-49f1-4b8e-b157-ed5d8a3e4476)

I dont think how its solved just fixed the easy part which was the account the harder part is to remake the score system's 70% to use standard functions which is not 2 hour like this was, the current version which stores data uses ac's vector which mix up standard variables

**Comment by NadalB** [comment]
i think its solved now

**Comment by Chobbz** [comment]
Looks like it !
